version: 2
jobs:
  Build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  Test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn run test
  DeployDevelopment:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "3f:4a:2f:31:59:94:c2:4d:b5:da:43:d6:4a:0d:3b:65"
      - run: yarn run build
      - run: scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@34.238.51.29:/var/www/html
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
workflows:
  version: 2
  HTML-Dev-Flow:
    jobs:
      - Build
      - Test:
          requires:
            - Build
      - DeployDevelopment:
        type: approval
          requires:
            - Build
            - Test