version: 2.1
jobs:
  Build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 
          name: Build-repo
          command: |
            sudo apt-get update
            ls
            
  Test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: 
          name: Prueba
          command: |
            echo "Esto es una prueba"
workflows:
 version: 2
 HTML-dev-flow:
   jobs:
     - Build
     - Hold-For-Approval:
         type: approval
         requires:
           - Build
     - Test:
         requires:
           - Hold-For-Approval
