version: 2.1
jobs:
  Build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: 
        command: |
          apt-get update
          apt-get install nginx -y
          ls -al           
  Test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: 
          name: Prueba
          command: |
            echo "Esto es una prueba"
workflows:
 version: 2
 HTML-dev-flow:
   jobs:
     - Build
     - Hold-For-Approval:
         type: approval
         requires:
           - Build
     - Test:
         requires:
           - Hold-For-Approval
