version: 2.1
jobs:
  Build:
    docker:
      - image: nginx:latest
    steps:
      - checkout
      - run: 
          name: Build-repo
          command: |
            ls     
  Test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install && npm -v
workflows:
 version: 2
 HTML-dev-flow:
   jobs:
     - Build
     - Hold-For-Approval:
         type: approval
         requires:
           - Build
     - Test:
         requires:
           - Hold-For-Approval
