version: 2.1
jobs:
  build:
    docker:
      image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: The first step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code has arrrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
