version: 2.1
jobs:
  Build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Build-repo
          command: |
            echo 'This is the delivery pipeline'
            ls -al           
  Run-With-Node:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run:
          name: Running In A Container With Node
          command: |
            node -v
  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Build-repo
     - Run-With-Node:
         requires:
           - Build-repo
     - Hold-For-Approval:
         type: approval
         requires:
           - Build-repo
           - Run-With-Node
     - Now-Complete:
         requires:
           - Hold-For-Approval
