version: 2.1
jobs:
  Build:
    docker:
      - image: ubuntu:latest
      - image: circleci/nginx:latest
    steps:
      - run:
          command: |
            ls -al           
      - checkout
  Test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: 
          name: Prueba
          command: |
            echo "Esto es una prueba"
workflows:
 version: 2
 HTML-dev-flow:
   jobs:
     - Build
     - Hold-For-Approval:
         type: approval
         requires:
           - Build
     - Test:
         requires:
           - Hold-For-Approval
